//~ component_text
//~ minecraft_minecraftclient
package com.spyxar.tiptapshow.config;

import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.*;
import net.minecraft.network.chat.Component;
import net.minecraft.client.Minecraft;
//? if >=26.1 {
import net.minecraft.client.gui.screens.Screen;
//?} else {
/*
import net.minecraft.client.gui.screen.Screen;
 *///?}

import java.awt.*;

public class YaclScreenFactory
{
    public static Screen getModConfigScreenFactory(Screen parent)
    {
        TipTapShowConfig.CONFIG.load();
        //ToDo: use defaults and config
        return YetAnotherConfigLib.createBuilder()
                .title(Component.translatable("config.tiptapshow.title"))
                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("config.tiptapshow.categories.general"))
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.tiptapshow.option.isenabled"))
                                .description(OptionDescription.of(Component.translatable("config.tiptapshow.description.isenabled")))
                                .binding(TipTapShowConfig.CONFIG.defaults().isEnabled, () -> TipTapShowConfig.CONFIG.instance().isEnabled, newVal -> TipTapShowConfig.CONFIG.instance().isEnabled = newVal)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .build())
                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("config.tiptapshow.categories.colors"))
                        .option(Option.<Color>createBuilder()
                                .name(Component.translatable("config.tiptapshow.option.backgroundcolor"))
                                .description(OptionDescription.of(Component.translatable("config.tiptapshow.description.backgroundcolor")))
                                .binding(TipTapShowConfig.CONFIG.defaults().backgroundColor, () -> TipTapShowConfig.CONFIG.instance().backgroundColor, newVal -> TipTapShowConfig.CONFIG.instance().backgroundColor = newVal)
                                .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(true))
                                .build())
                        .option(Option.<Color>createBuilder()
                                .name(Component.translatable("config.tiptapshow.option.pressedbackgroundcolor"))
                                .description(OptionDescription.of(Component.translatable("config.tiptapshow.description.pressedbackgroundcolor")))
                                .binding(TipTapShowConfig.CONFIG.defaults().pressedBackgroundColor, () -> TipTapShowConfig.CONFIG.instance().pressedBackgroundColor, newVal -> TipTapShowConfig.CONFIG.instance().pressedBackgroundColor = newVal)
                                .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(true))
                                .build())
                        .option(Option.<Color>createBuilder()
                                .name(Component.translatable("config.tiptapshow.option.keycolor"))
                                .description(OptionDescription.of(Component.translatable("config.tiptapshow.description.keycolor")))
                                .binding(TipTapShowConfig.CONFIG.defaults().keyColor, () -> TipTapShowConfig.CONFIG.instance().keyColor, newVal -> TipTapShowConfig.CONFIG.instance().keyColor = newVal)
                                .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(true))
                                .build())
                        .option(Option.<Color>createBuilder()
                                .name(Component.translatable("config.tiptapshow.option.pressedkeycolor"))
                                .description(OptionDescription.of(Component.translatable("config.tiptapshow.description.pressedkeycolor")))
                                .binding(TipTapShowConfig.CONFIG.defaults().pressedKeyColor, () -> TipTapShowConfig.CONFIG.instance().pressedKeyColor, newVal -> TipTapShowConfig.CONFIG.instance().pressedKeyColor = newVal)
                                .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(true))
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.tiptapshow.option.rainbowmode"))
                                .description(OptionDescription.of(Component.translatable("config.tiptapshow.description.rainbowmode")))
                                .binding(TipTapShowConfig.CONFIG.defaults().rainbowMode, () -> TipTapShowConfig.CONFIG.instance().rainbowMode, newVal -> TipTapShowConfig.CONFIG.instance().rainbowMode = newVal)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.tiptapshow.option.rainbowoffset"))
                                .description(OptionDescription.of(Component.translatable("config.tiptapshow.description.rainbowoffset")))
                                .binding(TipTapShowConfig.CONFIG.defaults().rainbowOffset, () -> TipTapShowConfig.CONFIG.instance().rainbowOffset, newVal -> TipTapShowConfig.CONFIG.instance().rainbowOffset = newVal)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(1, 10).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.tiptapshow.option.rainbowspeed"))
                                .description(OptionDescription.of(Component.translatable("config.tiptapshow.description.rainbowspeed")))
                                .binding(TipTapShowConfig.CONFIG.defaults().rainbowSpeed, () -> TipTapShowConfig.CONFIG.instance().rainbowSpeed, newVal -> TipTapShowConfig.CONFIG.instance().rainbowSpeed = newVal)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(1, 5).step(1))
                                .build())
                        .build())
                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("config.tiptapshow.categories.display"))
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.tiptapshow.option.roundedbackground"))
                                .description(OptionDescription.of(Component.translatable("config.tiptapshow.description.roundedbackground")))
                                .binding(TipTapShowConfig.CONFIG.defaults().roundedBackground, () -> TipTapShowConfig.CONFIG.instance().roundedBackground, newVal -> TipTapShowConfig.CONFIG.instance().roundedBackground = newVal)
                                .controller(TickBoxControllerBuilder::create)
                                .available(false)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.tiptapshow.option.renderindebughud"))
                                .description(OptionDescription.of(Component.translatable("config.tiptapshow.description.renderindebughud")))
                                .binding(TipTapShowConfig.CONFIG.defaults().renderInDebugHud, () -> TipTapShowConfig.CONFIG.instance().renderInDebugHud, newVal -> TipTapShowConfig.CONFIG.instance().renderInDebugHud = newVal)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.tiptapshow.option.renderingui"))
                                .description(OptionDescription.of(Component.translatable("config.tiptapshow.description.renderingui")))
                                .binding(TipTapShowConfig.CONFIG.defaults().renderInGui, () -> TipTapShowConfig.CONFIG.instance().renderInGui, newVal -> TipTapShowConfig.CONFIG.instance().renderInGui = newVal)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.tiptapshow.option.renderwhenplayerlistopen"))
                                .description(OptionDescription.of(Component.translatable("config.tiptapshow.description.renderwhenplayerlistopen")))
                                .binding(TipTapShowConfig.CONFIG.defaults().renderWhenPlayerListOpen, () -> TipTapShowConfig.CONFIG.instance().renderWhenPlayerListOpen, newVal -> TipTapShowConfig.CONFIG.instance().renderWhenPlayerListOpen = newVal)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("config.tiptapshow.option.keyshadow"))
                                .description(OptionDescription.of(Component.translatable("config.tiptapshow.description.keyshadow")))
                                .binding(TipTapShowConfig.CONFIG.defaults().keyShadow, () -> TipTapShowConfig.CONFIG.instance().keyShadow, newVal -> TipTapShowConfig.CONFIG.instance().keyShadow = newVal)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<TipTapShowConfig.CpsType>createBuilder()
                                .name(Component.translatable("config.tiptapshow.option.cpstype"))
                                .description(OptionDescription.of(Component.translatable("config.tiptapshow.description.cpstype")))
                                .binding(TipTapShowConfig.CONFIG.defaults().cpsType, () -> TipTapShowConfig.CONFIG.instance().cpsType, newVal -> TipTapShowConfig.CONFIG.instance().cpsType = newVal)
                                .controller(opt -> EnumControllerBuilder.create(opt)
                                        .enumClass(TipTapShowConfig.CpsType.class))
                                .build())
                        .option(Option.<Double>createBuilder()
                                .name(Component.translatable("config.tiptapshow.option.displayfactor"))
                                .description(OptionDescription.of(Component.translatable("config.tiptapshow.description.displayfactor")))
                                .binding(TipTapShowConfig.CONFIG.defaults().displayFactor, () -> TipTapShowConfig.CONFIG.instance().displayFactor, newVal -> TipTapShowConfig.CONFIG.instance().displayFactor = newVal)
                                .controller(opt -> DoubleSliderControllerBuilder.create(opt).range(1D, 10D).step(0.1D))
                                .build())
                        //? if >=26.1 {
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.tiptapshow.option.horizontalslider"))
                                .description(OptionDescription.of(Component.translatable("config.tiptapshow.description.horizontalslider")))
                                .binding(TipTapShowConfig.CONFIG.defaults().horizontalSlider, () -> TipTapShowConfig.CONFIG.instance().horizontalSlider, newVal -> TipTapShowConfig.CONFIG.instance().horizontalSlider = newVal)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, Minecraft.getInstance().getWindow().getGuiScale() * Minecraft.getInstance().getWindow().getGuiScaledWidth()).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.tiptapshow.option.verticalslider"))
                                .description(OptionDescription.of(Component.translatable("config.tiptapshow.description.verticalslider")))
                                .binding(TipTapShowConfig.CONFIG.defaults().verticalSlider, () -> TipTapShowConfig.CONFIG.instance().verticalSlider, newVal -> TipTapShowConfig.CONFIG.instance().verticalSlider = newVal)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, Minecraft.getInstance().getWindow().getGuiScale() * Minecraft.getInstance().getWindow().getGuiScaledHeight()).step(1))
                                .build())
                        //?} else {
                        /*.option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.tiptapshow.option.horizontalslider"))
                                .description(OptionDescription.of(Component.translatable("config.tiptapshow.description.horizontalslider")))
                                .binding(TipTapShowConfig.CONFIG.defaults().horizontalSlider, () -> TipTapShowConfig.CONFIG.instance().horizontalSlider, newVal -> TipTapShowConfig.CONFIG.instance().horizontalSlider = newVal)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, /^? =1.21.4 {^//^(int)^//^?}^/Minecraft.getInstance().getWindow().getScaleFactor() * Minecraft.getInstance().getWindow().getScaledWidth()).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("config.tiptapshow.option.verticalslider"))
                                .description(OptionDescription.of(Component.translatable("config.tiptapshow.description.verticalslider")))
                                .binding(TipTapShowConfig.CONFIG.defaults().verticalSlider, () -> TipTapShowConfig.CONFIG.instance().verticalSlider, newVal -> TipTapShowConfig.CONFIG.instance().verticalSlider = newVal)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, /^? =1.21.4 {^//^(int)^//^?}^/Minecraft.getInstance().getWindow().getScaleFactor() * Minecraft.getInstance().getWindow().getScaledHeight()).step(1))
                                .build())
                        *///?}
                        //ToDo: Use Component.translatable
                        .option(ButtonOption.createBuilder()
                                .name(Component.literal("Change position"))
                                .description(OptionDescription.of(Component.literal("Click this button to open a GUI to position the overlay")))
                                .text(Component.literal("Open"))
                                // ToDo: set yaclScreen as previous parameter? Have to make sure horizontal/vertical slider values change according to PositionGui though
                                .action((yaclScreen, buttonOption) -> Minecraft.getInstance()/*? >=26.2 {*/.gui/*?}*/.setScreen(new PositionGui(null)))
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("config.tiptapshow.categories.keydisplay"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("config.tiptapshow.option.showmovement"))
                                        .description(OptionDescription.of(Component.translatable("config.tiptapshow.description.showmovement")))
                                        .binding(TipTapShowConfig.CONFIG.defaults().showMovement, () -> TipTapShowConfig.CONFIG.instance().showMovement, newVal -> TipTapShowConfig.CONFIG.instance().showMovement = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("config.tiptapshow.option.showjump"))
                                        .description(OptionDescription.of(Component.translatable("config.tiptapshow.description.showjump")))
                                        .binding(TipTapShowConfig.CONFIG.defaults().showJump, () -> TipTapShowConfig.CONFIG.instance().showJump, newVal -> TipTapShowConfig.CONFIG.instance().showJump = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("config.tiptapshow.option.showclick"))
                                        .description(OptionDescription.of(Component.translatable("config.tiptapshow.description.showclick")))
                                        .binding(TipTapShowConfig.CONFIG.defaults().showClick, () -> TipTapShowConfig.CONFIG.instance().showClick, newVal -> TipTapShowConfig.CONFIG.instance().showClick = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        .build())
                .save(TipTapShowConfig.CONFIG::save)
                .build()
                .generateScreen(parent);
    }
}